# Generated by Django 5.0.9 on 2024-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('active', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Reasoning',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('yc', models.CharField(max_length=64)),
                ('gn', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('rank', models.CharField(max_length=64)),
                ('score', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
