# Generated by Django 5.0.9 on 2024-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('username', models.CharField(max_length=64, verbose_name='姓名')),
                ('email', models.EmailField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('education', models.CharField(choices=[('bachelor', '学士'), ('master', '硕士'), ('doctor', '博士')], max_length=20, verbose_name='最高学历')),
                ('university', models.CharField(max_length=100, verbose_name='毕业院校')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('experience', models.CharField(choices=[('1-3', '1-3年'), ('3-5', '3-5年'), ('5-10', '5-10年'), ('10+', '10年以上')], max_length=20, verbose_name='从业经验')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='执业医师资格证号码')),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='doctor_licenses/', verbose_name='资格证扫描件')),
                ('title', models.CharField(choices=[('resident', '住院医师'), ('attending', '主治医师'), ('associate', '副主任医师'), ('chief', '主任医师')], max_length=20, verbose_name='专业职称')),
                ('departments', models.JSONField(verbose_name='执业科室')),
                ('workplace', models.CharField(max_length=200, verbose_name='执业地点')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
            ],
        ),
    ]
